apiVersion: v1

kind: Service

metadata:
  name: coinnews-webserver-service

spec:
  type: NodePort

  selector:
    app: webserver

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000