apiVersion: batch/v1
kind: CronJob
metadata:
  name: bepa-cronjob
spec:
  schedule: "*/5 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: coinnews-bepa-cronjob
              image: amirparsa/bepa_cronjob:latest
              # Add additional container settings as needed
              env:
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: coinnews-secret
                      key: POSTGRES_USER
                      
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: coinnews-secret
                      key: POSTGRES_PASSWORD
                
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: coinnews-secret
                      key: POSTGRES_DB

                - name: MAILGUN_DOMAIN
                  valueFrom:
                    secretKeyRef:
                      name: coinnews-secret
                      key: MAILGUN_DOMAIN
                
                - name: MAILGUN_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: coinnews-secret
                      key: MAILGUN_API_KEY

                - name: POSTGRES_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: coinnews-configmap
                      key: POSTGRES_HOST

                - name: POSTGRES_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: coinnews-configmap
                      key: POSTGRES_PORT
                
                - name: COIN_NEWS_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: coinnews-configmap
                      key: COIN_NEWS_HOST

                - name: MAILGUN_USER_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: coinnews-configmap
                      key: MAILGUN_USER_NAME
                      
          restartPolicy: OnFailure  # Restart the container if the job fails